#!/usr/bin/env python3
import os

import sys
from termcolor import cprint

from pywiface.interface import WirelessInterface, MonitorInterface

if os.uid() != 0:
    cprint('Error: Must be run as root!', 'red')
    raise SystemExit

if len(sys.argv) == 1:
    print("Usage: pywiface command interface [options]")
    print("Valid commands: mon chan")
    raise SystemExit

if sys.argv[1] == 'mon':
    if len(sys.argv == 2):
        print("Usage: pywiface mon interface start|stop")
        raise SystemExit
    if sys.argv[3] in ['start', 'true', 'on']:
        interface = MonitorInterface(name=sys.argv[2])
        print("Enabled monitor mode on", interface.name)
    else:
        interface = WirelessInterface(name=sys.argv[2])
        interface.set_managed_mode()
        print("Disabled monitor mode on", interface.name)
elif sys.argv[1] == 'chan':
    if len(sys.argv == 2):
        print("Usage: pywiface chan interface channel")
        raise SystemExit
    if 0 < sys.argv[3] <= 14:
        interface = WirelessInterface(name=sys.argv[2])
        interface.channel == sys.argv[3]
        print("Channel set to", sys.argv[3], "on", interface.name)
